name: Run Python Script

# Controls when the action will run.
on:
  schedule:
    - cron: '*/3 * * * *'  # This runs the job every 2 minute
  workflow_dispatch:  # Allows manual triggers for testing

jobs:
  run-script:
    runs-on: ubuntu-latest  # The environment to run the script on (Linux)
    
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3  # This checks out the repository code

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.3'  # Define the Python version you want to use

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Python script
      run: |
        python Ping.py  
        
      # Replace this with your Python script path
