name: Run Python Script on Webhook Trigger


on:
  workflow_dispatch: # allows manual triggers via GitHub UI
  repository_dispatch: # this is the webhook trigger event

jobs:
  run-script:
    runs-on: ubuntu-latest

    permissions:
      actions: write
      contents: read
      

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.3'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Python script
      run: |
        python Ping.py

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2.0.6
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
          retain_days: 1  # Retain workflow runs from the last 1 days
          
            
